#!/bin/sh
set -efu

PYS=${PYS:-"$(pyversions -r 2>/dev/null)"}

cd "$AUTOPKGTEST_TMP"

for py in $PYS; do
    echo "=== $py ==="
    $py /usr/lib/$py/dist-packages/tornado/test/runtests.py --verbose 2>&1
done
